### ISSUE TITLE
Aggregated tables for non default segmentations

### ISSUE THREAD

**Issue by kvshams** [broadinstitute/cellprofiler-on-Terra#11]
In the default configuration, Cytomining aggregation is based on cell, cytoplasm, and nuclei.

Is it possible to include more segmentations like if include a different secondary object (finding vacuoles) in the aggregated table.

Thanks,
Shams

**Comment by carmendv** [comment]
Hi Shams, 
Have you try to aggregate a small dataset (like 2 wells) using pycytominer? I think it allows for non canonical compartments ([here](https://github.com/cytomining/pycytominer/blob/master/pycytominer/cyto_utils/cells.py#L40)). If you want us to have this attribute as an input we can incorporate it.
However, if I remember right, the limitation for your dataset comes from sqlite column limits (SQLITE_MAX_COLUMN), which is by default 2000. Therefore when aggregating cellpainting type of datasets with many columns is not possible. I believe pycytominer is planning to move from sqlite to parquet, and that could solve this limitation, you can read more about it [here](https://github.com/cytomining/pycytominer/issues?q=is%3Aissue+is%3Aopen+parquet). 
Currently, we are not supporting parquet since it is a functionality still under development. I can leave this issue open and we could come back to it in the future.
