### ISSUE TITLE
Tolerate `images_directory_gsurl` values with a final slash 

### ISSUE THREAD

**Issue by deflaux** [broadinstitute/cellprofiler-on-Terra#12]
I was passing a GCS URL with a final slash and that caused the workflow to fail. See https://job-manager.dsde-prod.broadinstitute.org/jobs/e67da343-7a05-454d-aa53-6479e1a481d8

Suggestion: consider updating the workflow to be tolerant of a final slash if users include it.

Thanks very much for these great workflows!

**Comment by sjfleming** [comment]
Actually I realized I didn't do this quite right...

It works fine, but the caveat is that now there are two visible inputs to the WDL for the input directory, for example:

one is required
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/10214815/181870893-0a78ad01-d834-4bef-a903-62a75e1460a1.png">

and one is optional
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/10214815/181870896-bc029140-9a14-4f03-91e6-52f24845139e.png">

The second optional one should not exist!  It exists because I did the `String` manipulation inside the `input` block, when I should do it after the `input` block.  I will fix this.
